language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm --prefix ./docs run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm --prefix ./docs run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
